app:
  # Should be the same as backend.baseUrl when using the `app-backend` plugin
  title: Developer Portal
  baseUrl: https://${WEBSITE_HOSTNAME}

backend:
  baseUrl: https://${WEBSITE_HOSTNAME}
  listen:
    port: 7007

  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      ssl: true

techdocs:
  builder: 'local'
  generator:
    runIn: 'local'
  publisher:
    type: 'azureBlobStorage'
    azureBlobStorage:
      containerName: 'techdocs'
      credentials:
        accountName: ${STORAGE_ACCOUNT_NAME}
        accountKey: ${STORAGE_ACCOUNT_KEY}
